/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controlasistencia;

import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import mdlaf.MaterialLookAndFeel;
import mdlaf.animation.MaterialUIMovement;
import mdlaf.themes.MaterialLiteTheme;
import mdlaf.utils.MaterialColors;

/**
 *
 * @author BB_TLACUACHE
 */
public class HOME extends javax.swing.JFrame {
    
    InputStream ttf_;
    Font OswaldLight,PTSans_Bold,PTSans_Bi,PTSans_I,PTSans_Regular;
        
    /**
     * Creates new form HOME
     */
    public HOME() {
        try {
            //FONT - ENCABEZADOS
            this.ttf_= HOME.class.getClass().getResourceAsStream("/fonts/Oswald-Light.ttf");
            this.OswaldLight = Font.createFont(Font.TRUETYPE_FONT, ttf_);
            this.OswaldLight = OswaldLight.deriveFont(30f);
            
            //FONT - BOTONES
            this.ttf_= HOME.class.getClass().getResourceAsStream("/fonts/PTSans-Bold.ttf");
            this.PTSans_Bold = Font.createFont(Font.TRUETYPE_FONT, ttf_);
            this.PTSans_Bold = this.PTSans_Bold.deriveFont(18f);
            
            this.ttf_= HOME.class.getClass().getResourceAsStream("/fonts/PTSans-BoldItalic.ttf");
            this.PTSans_Bi = Font.createFont(Font.TRUETYPE_FONT, ttf_);
            
            this.ttf_= HOME.class.getClass().getResourceAsStream("/fonts/PTSans-Italic.ttf");
            this.PTSans_I = Font.createFont(Font.TRUETYPE_FONT, ttf_);
            
            this.ttf_= HOME.class.getClass().getResourceAsStream("/fonts/PTSans-Regular.ttf");
            this.PTSans_Regular = Font.createFont(Font.TRUETYPE_FONT, ttf_);
            this.PTSans_Regular = this.PTSans_Regular.deriveFont(18f);
            
            initComponents();
            
        } catch (FontFormatException ex) {
            Logger.getLogger(HOME.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(HOME.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JPanel();
        Contenido = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        regEmp = new javax.swing.JButton();
        consEmp = new javax.swing.JButton();
        regHor = new javax.swing.JButton();
        consHor = new javax.swing.JButton();
        cargar = new javax.swing.JButton();
        consAsis = new javax.swing.JButton();
        consInci = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Control de asistencia");
        setAutoRequestFocus(false);
        setBounds(new java.awt.Rectangle(200, 100, 0, 0));
        setIconImages(null);
        setMaximumSize(new java.awt.Dimension(1026, 684));
        setName("frame"); // NOI18N
        setResizable(false);

        Menu.setBackground(new java.awt.Color(77, 175, 115));
        Menu.setName("Menu"); // NOI18N
        Menu.setPreferredSize(new java.awt.Dimension(1026, 684));

        Contenido.setBackground(new java.awt.Color(233, 209, 153));
        Contenido.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Contenido.setMaximumSize(new java.awt.Dimension(770, 684));
        Contenido.setMinimumSize(new java.awt.Dimension(770, 684));
        Contenido.setName("Contenido"); // NOI18N
        Contenido.setPreferredSize(new java.awt.Dimension(770, 684));

        javax.swing.GroupLayout ContenidoLayout = new javax.swing.GroupLayout(Contenido);
        Contenido.setLayout(ContenidoLayout);
        ContenidoLayout.setHorizontalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        ContenidoLayout.setVerticalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 684, Short.MAX_VALUE)
        );

        jLabel1.setBackground(new java.awt.Color(224, 224, 226));
        jLabel1.setFont(OswaldLight);
        jLabel1.setForeground(new java.awt.Color(77, 175, 115));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Empleados  ");
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(89, 29));

        jLabel2.setBackground(new java.awt.Color(224, 224, 226));
        jLabel2.setFont(OswaldLight);
        jLabel2.setForeground(new java.awt.Color(77, 175, 115));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Horarios  ");
        jLabel2.setOpaque(true);

        jLabel3.setBackground(new java.awt.Color(224, 224, 226));
        jLabel3.setFont(OswaldLight);
        jLabel3.setForeground(new java.awt.Color(77, 175, 115));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Asistencias  ");
        jLabel3.setMaximumSize(new java.awt.Dimension(89, 29));
        jLabel3.setMinimumSize(new java.awt.Dimension(89, 29));
        jLabel3.setOpaque(true);
        jLabel3.setPreferredSize(new java.awt.Dimension(89, 29));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(52, 46, 55));
        jLabel4.setText("Cargar archivo");

        regEmp.setBackground(new java.awt.Color(77, 175, 115));
        regEmp.setFont(PTSans_Bold);
        regEmp.setForeground(new java.awt.Color(224, 224, 226));
        regEmp.addMouseListener(MaterialUIMovement.getMovement( regEmp,new java.awt.Color(52,46,55)));
        regEmp.setText("Registrar");
        regEmp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(77, 175, 115), 2));
        regEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        regEmp.setFocusPainted(false);
        regEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regEmpActionPerformed(evt);
            }
        });

        consEmp.setBackground(new java.awt.Color(77, 175, 115));
        consEmp.setFont(PTSans_Bold);
        consEmp.setForeground(new java.awt.Color(224, 224, 226));
        consEmp.addMouseListener(MaterialUIMovement.getMovement( consEmp,new java.awt.Color(52,46,55) ));
        consEmp.setText("Consultar");
        consEmp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(77, 175, 115), 2));
        consEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        consEmp.setFocusPainted(false);
        consEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consEmpActionPerformed(evt);
            }
        });

        regHor.setBackground(new java.awt.Color(77, 175, 115));
        regHor.setFont(PTSans_Bold);
        regHor.setForeground(new java.awt.Color(224, 224, 226));
        regHor.addMouseListener(MaterialUIMovement.getMovement( regHor,new java.awt.Color(52,46,55) ));
        regHor.setText("Registrar");
        regHor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(77, 175, 115), 2));
        regHor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        regHor.setFocusPainted(false);
        regHor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regHorActionPerformed(evt);
            }
        });

        consHor.setBackground(new java.awt.Color(77, 175, 115));
        consHor.setFont(PTSans_Bold);
        consHor.setForeground(new java.awt.Color(224, 224, 226));
        consHor.addMouseListener(MaterialUIMovement.getMovement( consHor,new java.awt.Color(52,46,55)));
        consHor.setText("Consultar");
        consHor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(77, 175, 115), 2));
        consHor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        consHor.setFocusPainted(false);
        consHor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consHorActionPerformed(evt);
            }
        });

        cargar.setBackground(new java.awt.Color(52, 46, 55));
        cargar.setFont(PTSans_Bold);
        cargar.setForeground(new java.awt.Color(224, 224, 226));
        cargar.addMouseListener(MaterialUIMovement.getMovement( cargar,new java.awt.Color(119,47,91) ));
        cargar.setText("+");
        cargar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(77, 175, 115), 2));
        cargar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cargar.setFocusPainted(false);
        cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarActionPerformed(evt);
            }
        });

        consAsis.setBackground(new java.awt.Color(77, 175, 115));
        consAsis.setFont(PTSans_Bold);
        consAsis.setForeground(new java.awt.Color(52, 46, 55));
        consAsis.addMouseListener(MaterialUIMovement.getMovement( consAsis,new java.awt.Color(224,224,226) ));
        consAsis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/asistencia.png"))); // NOI18N
        consAsis.setText("Consultar asistencia");
        consAsis.setHorizontalAlignment(SwingConstants.LEFT);
        consAsis.setBorder(null);
        consAsis.setBorderPainted(false);
        consAsis.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        consAsis.setFocusPainted(false);
        consAsis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consAsisActionPerformed(evt);
            }
        });

        consInci.setBackground(new java.awt.Color(77, 175, 115));
        consInci.setFont(PTSans_Bold);
        consInci.setForeground(new java.awt.Color(52, 46, 55));
        consInci.addMouseListener(MaterialUIMovement.getMovement( consInci,new java.awt.Color(224,224,226) ));
        consInci.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inasistencia.png"))); // NOI18N
        consInci.setHorizontalAlignment(SwingConstants.LEFT);
        consInci.setText("Consultar incidencias");
        consInci.setToolTipText("");
        consInci.setBorder(null);
        consInci.setBorderPainted(false);
        consInci.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        consInci.setFocusPainted(false);
        consInci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consInciActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(regEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(consEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(regHor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(consHor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(consAsis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(consInci, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cargar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(Contenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addComponent(Contenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(regEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(regHor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consHor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cargar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consAsis, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consInci, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Contenido.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        java.net.URL url = ClassLoader.getSystemResource("imagenes/icon.png");
        Toolkit kit = Toolkit.getDefaultToolkit();
        Image img = kit.createImage(url);
        setIconImage(img);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regEmpActionPerformed

    private void consEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consEmpActionPerformed

    private void regHorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regHorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regHorActionPerformed

    private void consHorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consHorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consHorActionPerformed

    private void cargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cargarActionPerformed

    private void consAsisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consAsisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consAsisActionPerformed

    private void consInciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consInciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consInciActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            UIManager.setLookAndFeel (new MaterialLookAndFeel( new MaterialLiteTheme() ));
        }
        catch (UnsupportedLookAndFeelException e) {
            e.printStackTrace ();
        }
        
        System.out.println(MaterialColors.LIGHT_BLUE_400);

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HOME().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenido;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton cargar;
    private javax.swing.JButton consAsis;
    private javax.swing.JButton consEmp;
    private javax.swing.JButton consHor;
    private javax.swing.JButton consInci;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton regEmp;
    private javax.swing.JButton regHor;
    // End of variables declaration//GEN-END:variables
}
