/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controlasistencia;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import mdlaf.animation.MaterialUIMovement;

/**
 *
 * @author BB_TLACUACHE
 */
public class InicioSesion extends javax.swing.JFrame {

    /**
     * Creates new form InicioSesion
     */
    Fonts fts = new Fonts();
    int numero;
    public InicioSesion() {
        numero = (int)(Math.random()*(999-101+1)+101);
        initComponents();
        lbl_captcha.setText(String.valueOf(numero));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ingresar = new javax.swing.JButton();
        usuario = new javax.swing.JTextField();
        contra = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_captcha = new javax.swing.JLabel();
        captcha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(470, 170));

        jPanel1.setBackground(new java.awt.Color(215, 124, 101));

        jPanel2.setBackground(new java.awt.Color(52, 46, 55));

        ingresar.setBackground(new java.awt.Color(224, 224, 226));
        ingresar.setFont(Fonts.PTSans_Bold);
        ingresar.setForeground(new java.awt.Color(52, 46, 55));
        ingresar.setText("Iniciar sesión");
        ingresar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52, 46, 55), 2));
        ingresar.addMouseListener(MaterialUIMovement.getMovement( ingresar,new java.awt.Color(209,87,129) ));
        ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ingresar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        usuario.setFont(fts.PTSans_Regular_12);
        usuario.setForeground(new java.awt.Color(52, 46, 55));
        usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usuarioKeyTyped(evt);
            }
        });

        contra.setFont(fts.PTSans_Regular_12);
        contra.setForeground(new java.awt.Color(52, 46, 55));
        contra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contraKeyTyped(evt);
            }
        });

        jLabel1.setFont(Fonts.PTSans_Regular);
        jLabel1.setText("Usuario");

        jLabel2.setFont(Fonts.PTSans_Regular);
        jLabel2.setText("Contraseña");

        jLabel3.setBackground(new java.awt.Color(52, 46, 55));
        jLabel3.setFont(fts.OswaldLight);
        jLabel3.setForeground(new java.awt.Color(224, 224, 226));
        jLabel3.setText("                     Inicio de sesión");
        jLabel3.setOpaque(true);

        lbl_captcha.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_captcha.setForeground(new java.awt.Color(52, 46, 55));
        lbl_captcha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_captcha.setText("123");
        lbl_captcha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52, 46, 55)));

        captcha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                captchaKeyTyped(evt);
            }
        });

        jLabel4.setFont(fts.PTSans_Regular);
        jLabel4.setText("Captcha");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(usuario)
                                .addComponent(contra, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(captcha, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_captcha, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(contra, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(captcha, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_captcha, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usuarioKeyTyped
        char c = evt.getKeyChar();
        if (usuario.getText().length() > 29){
            evt.consume();
        }
    }//GEN-LAST:event_usuarioKeyTyped

    private void contraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contraKeyTyped
        char c = evt.getKeyChar();
        if (contra.getText().length() > 29){
            evt.consume();
        }
    }//GEN-LAST:event_contraKeyTyped

    private void captchaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_captchaKeyTyped
        char c = evt.getKeyChar();
        if (c<'0' || c>'9'||captcha.getText().length() > 2){
            evt.consume();
        }
    }//GEN-LAST:event_captchaKeyTyped

    private void ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarActionPerformed

        if(Extras.isNull(usuario.getText())||Extras.isNull(contra.getText())||Extras.isNull(captcha.getText())){
            usuario.setText("");
            contra.setText("");
            captcha.setText("");
            JOptionPane optionPane = new JOptionPane();
            optionPane.showMessageDialog(null,"        Aún hay campos vacíos         ", "    ERROR!!", JOptionPane.INFORMATION_MESSAGE);
        }else{
            if(captcha.getText().equals(String.valueOf(numero))){
                try {
                    QuerysBD consulta = new QuerysBD();
                    String exito = consulta.logIn(usuario.getText(),contra.getText());
                    if(exito.equals("0")){
                        JOptionPane optionPane = new JOptionPane();
                        optionPane.showMessageDialog(null,"        Credenciales incorrectas         ", "    ERROR!!", JOptionPane.INFORMATION_MESSAGE);
                    }else{
                        new HOME().setVisible(true);
                        this.dispose();
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(InicioSesion.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                captcha.setText("");
                JOptionPane optionPane = new JOptionPane();
                optionPane.showMessageDialog(null,"        El captcha no coincide         ", "    ERROR!!", JOptionPane.INFORMATION_MESSAGE);
                
            } 
        }
    }//GEN-LAST:event_ingresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField captcha;
    private javax.swing.JPasswordField contra;
    private javax.swing.JButton ingresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_captcha;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
